var dateformats = [
{'locale': 'ar', 'dateformat': 'DD/MM/YY'},
{'locale': 'eu', 'dateformat': 'M/D/YY'},
{'locale': 'ca_ES', 'dateformat': 'DD/MM/YY'},
{'locale': 'en_AU', 'dateformat': 'DD/MM/YY'},
{'locale': 'en_GB', 'dateformat': 'DD/MM/YY'},
{'locale': 'en_NZ', 'dateformat': 'D/MM/YY'},
{'locale': 'en_PL', 'dateformat': 'DD/MM/YY'},
{'locale': 'en_US', 'dateformat': 'MM/DD/YY'},
{'locale': 'en_ZA', 'dateformat': 'YYYY/MM/DD'},
{'locale': 'es_MX', 'dateformat': 'D/MM/YY'},
{'locale': 'es_ES', 'dateformat': 'D/MM/YY'},
{'locale': 'fr_CA', 'dateformat': 'YY-MM-DD'},
{'locale': 'fr_FR', 'dateformat': 'DD/MM/YY'},
{'locale': 'ja_JP', 'dateformat': 'YY/MM/DD'},
{'locale': 'ko_KR', 'dateformat': 'YY. M. D'},
{'locale': 'mn', 'dateformat': 'M/D/YY'},
{'locale': 'nl_NL', 'dateformat': 'D-M-YY'},
{'locale': 'pt_BR', 'dateformat': 'DD/MM/YY'},
{'locale': 'pt_PT', 'dateformat': 'DD-MM-YYYY'},
{'locale': 'ru_RU', 'dateformat': 'DD.MM.YY'},
{'locale': 'sv_SE', 'dateformat': 'YYYY-MM-DD'},
{'locale': 'tr_TR', 'dateformat': 'DD.MM.YYYY'},
{'locale': 'vi_VN', 'dateformat': 'DD/MM/YYYY'},
{'locale': 'zh_CN', 'dateformat': 'YY-M-D'},
{'locale': 'zh_TW', 'dateformat': 'YYYY/M/D'},
];